export default [
  {
    row: 1,
    ID: 'nation',
    Name: 'Nation',
    GeoIdField: 'GEOID',
    DisplayField: 'NAME',
    TigerIdField: 'NATION',
    TigerFIPSFields: ['NATION'],
    DataAPIIdField: 'us',
    DataAPIFIPSFields: ['us'],
    ConsumerDataIdField: 'ID',
    MapTigerId: false,
    MapStateId: false,
    GeoComparisonDisplayOrder: 7,
    GeoCode: ['010'],
    IsForComparisonOnly: true,
    DefaultGeoId: '1',
    DefaultGeoName: 'U.S.',
  },
  {
    row: 2,
    ID: 'state',
    Name: 'State',
    GeoIdField: 'GEOID',
    DisplayField: 'NAME',
    TigerIdField: 'STATE',
    TigerFIPSFields: ['STATE'],
    DataAPIIdField: 'state',
    DataAPIFIPSFields: ['state'],
    ConsumerDataIdField: 'ID',
    MapTigerId: false,
    MapStateId: true,
    GeoComparisonDisplayOrder: 6,
    GeoCode: ['040'],
    IsForComparisonOnly: false,
    Label: 'State or equivalent area (DC, PR) level data',
    ServiceEndpoints: [
      '${generalizedGeoDataAPIUrl}/13',
      '${generalizedGeoDataAPIUrl}/12',
      '${generalizedGeoDataAPIUrl}/11',
    ],
    CompareToTypes: ['nation'],
    SupportsDynamicGeos: false,
    HasReport: true,
    DefaultDataVariableId: '1',
    DataPanelVariableIds: ['1', '15', '17', '64', '33', '5'],
    drawingProperties: {
      DisableBelow: 3,
      ZoomLevels: [
        { from: 0, to: 11 },
        { from: 12, to: 16 },
        { from: 17, to: 30 },
      ],
      AllowLabels: false,
    },
    IsSearchable: true,
    SearchFields: ['BASENAME'],
    ServiceIndexForSearch: 2,
  },
  {
    row: 3,
    ID: 'metro',
    Name: 'Metro',
    GeoIdField: 'GEOID',
    DisplayField: 'NAMELSAD',
    TigerIdField: 'CBSAFP',
    TigerFIPSFields: ['CBSAFP'],
    DataAPIIdField:
      'metropolitan statistical area/micropolitan statistical area',
    DataAPIFIPSFields: [
      'metropolitan statistical area/micropolitan statistical area',
    ],
    ConsumerDataIdField: 'ID',
    MapTigerId: false,
    MapStateId: false,
    GeoComparisonDisplayOrder: 5,
    GeoCode: ['310'],
    IsForComparisonOnly: false,
    Label: 'Metropolitan statistical area/micropolitan statistical area',
    ServiceEndpoints: [
      '${generalizedGeoDataAPIUrl}/16',
      '${generalizedGeoDataAPIUrl}/15',
      '${generalizedGeoDataAPIUrl}/14',
    ],
    CompareToTypes: ['nation'],
    SupportsDynamicGeos: false,
    HasReport: true,
    DefaultDataVariableId: '1',
    DataPanelVariableIds: ['1', '15', '17', '64', '33', '5'],
    drawingProperties: {
      DisableBelow: 3,
      ZoomLevels: [
        { from: 0, to: 11 },
        { from: 12, to: 16 },
        { from: 17, to: 30 },
      ],
      AllowLabels: false,
    },
    IsSearchable: true,
    SearchFields: ['BASENAME'],
    ServiceIndexForSearch: 2,
  },
  {
    row: 4,
    ID: 'county',
    Name: 'County',
    GeoIdField: 'GEOID',
    DisplayField: 'NAME',
    TigerIdField: 'COUNTY',
    TigerFIPSFields: ['STATE', 'COUNTY'],
    DataAPIIdField: 'county',
    DataAPIFIPSFields: ['state', 'county'],
    ConsumerDataIdField: 'ID',
    MapTigerId: false,
    MapStateId: false,
    GeoComparisonDisplayOrder: 4,
    GeoCode: ['050'],
    IsForComparisonOnly: false,
    TigerPartitionFields: ['STATE'],
    DataAPIPartitionFields: ['state'],
    StateField: 'STATE',
    Label:
      'County or equivalent area (Parish, Borough) level data (NOTE: If greyed out, zoom map in)',
    ServiceEndpoints: [
      '${generalizedGeoDataAPIUrl}/7',
      '${generalizedGeoDataAPIUrl}/6',
      '${generalizedGeoDataAPIUrl}/5',
    ],
    CompareToTypes: ['state', 'nation'],
    SupportsDynamicGeos: false,
    HasReport: true,
    DefaultDataVariableId: '1',
    DataPanelVariableIds: ['1', '15', '17', '64', '33', '5'],
    drawingProperties: {
      DisableBelow: 3,
      ZoomLevels: [
        { from: 0, to: 11 },
        { from: 12, to: 16 },
        { from: 17, to: 30 },
      ],
      AllowLabels: false,
    },
    IsSearchable: true,
    SearchFields: ['BASENAME'],
    ServiceIndexForSearch: 2,
  },
  {
    row: 5,
    ID: 'place',
    Name: 'City/Town',
    GeoIdField: 'GEOID',
    DisplayField: 'NAME',
    TigerIdField: 'PLACE',
    TigerFIPSFields: ['STATE', 'PLACE'],
    DataAPIIdField: 'place',
    DataAPIFIPSFields: ['state', 'place'],
    ConsumerDataIdField: 'ID',
    MapTigerId: true,
    MapStateId: false,
    GeoComparisonDisplayOrder: 3,
    GeoCode: ['160', '060'],
    IsForComparisonOnly: false,
    TigerPartitionFields: ['STATE'],
    DataAPIPartitionFields: ['state'],
    StateField: 'STATE',
    Label:
      'Economic Place (Incorporated city or Census Designated Place), or County Subdivision (New England states) level data (NOTE: If greyed out, zoom map in)',
    ServiceEndpoints: [
      '${generalizedGeoDataAPIUrl}/4',
      '${generalizedGeoDataAPIUrl}/3',
      '${generalizedGeoDataAPIUrl}/2',
    ],
    CompareToTypes: ['state', 'nation'],
    SupportsDynamicGeos: false,
    HasReport: true,
    DefaultDataVariableId: '1',
    DataPanelVariableIds: ['1', '15', '17', '64', '33', '5'],
    drawingProperties: {
      DisableBelow: 9,
      ZoomLevels: [
        { from: 0, to: 11 },
        { from: 12, to: 16 },
        { from: 17, to: 30 },
      ],
      AllowLabels: false,
    },
    IsSearchable: true,
    SearchFields: ['BASENAME'],
    ServiceIndexForSearch: 2,
  },
  {
    row: 6,
    ID: 'zcta',
    Name: 'ZIP Code',
    GeoIdField: 'GEOID',
    DisplayField: 'BASENAME',
    TigerIdField: 'ZCTA5',
    TigerFIPSFields: ['STATE', 'ZCTA5'],
    DataAPIIdField: 'zip code tabulation area',
    DataAPIFIPSFields: ['state', 'zip code tabulation area'],
    ConsumerDataIdField: 'ID',
    MapTigerId: false,
    MapStateId: false,
    GeoComparisonDisplayOrder: 2,
    GeoCode: ['860'],
    IsForComparisonOnly: false,
    TigerPartitionFields: ['STATE'],
    DataAPIPartitionFields: ['state'],
    Label:
      'ZIP Code or ZIP Code Tabulation Area (ZCTA) level data (NOTE: If greyed out, zoom map in)',
    ServiceEndpoints: [
      '${generalizedGeoDataAPIUrl}/10',
      '${generalizedGeoDataAPIUrl}/9',
      '${generalizedGeoDataAPIUrl}/8',
    ],
    CompareToTypes: ['state', 'nation'],
    SupportsDynamicGeos: false,
    HasReport: true,
    DefaultDataVariableId: '1',
    DataPanelVariableIds: ['1', '61', '15', '17', '64', '5'],
    drawingProperties: {
      DisableBelow: 9,
      ZoomLevels: [
        { from: 0, to: 11 },
        { from: 12, to: 16 },
        { from: 17, to: 30 },
      ],
      AllowLabels: true,
      DisableLabelsBelow: 9,
      LabelZoomLevels: [
        { from: 0, to: 14 },
        { from: 15, to: 30 },
      ],
      LabelFontSize: [13, 18],
      LabelExpression: '[BASENAME]',
    },
    IsSearchable: true,
    SearchFields: ['BASENAME'],
    ServiceIndexForSearch: 2,
  },
  {
    row: 7,
    ID: 'tract',
    Name: 'Tract',
    GeoIdField: 'GEOID',
    DisplayField: 'NAME',
    TigerIdField: 'TRACT',
    TigerFIPSFields: ['STATE', 'COUNTY', 'TRACT'],
    DataAPIIdField: 'tract',
    DataAPIFIPSFields: ['state', 'county', 'tract'],
    ConsumerDataIdField: 'ID',
    MapTigerId: false,
    MapStateId: false,
    GeoComparisonDisplayOrder: 1,
    GeoCode: ['140'],
    IsForComparisonOnly: false,
    TigerPartitionFields: ['STATE', 'COUNTY'],
    DataAPIPartitionFields: ['state', 'county'],
    StateField: 'STATE',
    Label: 'Census Tract level data (NOTE: If greyed out, zoom map in)',
    ServiceEndpoints: [
      '${generalizedGeoDataAPIUrl}/1',
      '${generalizedGeoDataAPIUrl}/0',
    ],
    CompareToTypes: ['county', 'state', 'nation'],
    SupportsDynamicGeos: false,
    HasReport: true,
    DefaultDataVariableId: '1',
    DataPanelVariableIds: ['1', '61', '15', '17', '64', '5'],
    drawingProperties: {
      DisableBelow: 9,
      ZoomLevels: [
        { from: 0, to: 16 },
        { from: 17, to: 30 },
      ],
      AllowLabels: true,
      DisableLabelsBelow: 9,
      LabelZoomLevels: [
        { from: 0, to: 14 },
        { from: 15, to: 30 },
      ],
      LabelFontSize: [13, 18],
      LabelExpression: '[BASENAME]',
    },
    IsSearchable: true,
    SearchFields: ['BASENAME'],
    ServiceIndexForSearch: 1,
  },
];
