export default [
  {
    row: 1,
    Event: 'industryChanged',
    PanelName: 'industrySelection',
    Display: false,
  },
  {
    row: 2,
    Event: 'industryChanged',
    PanelName: 'geoSearch',
    Display: false,
  },
  {
    row: 3,
    Event: 'industryChanged',
    PanelName: 'dataVariableSelection',
    Display: false,
  },
  { row: 5, Event: 'industryChanged', PanelName: 'dashboard', Display: true },
  { row: 6, Event: 'industryChanged', PanelName: 'legend', Display: true },
  {
    row: 7,
    Event: 'geoTypeChanged',
    PanelName: 'industrySelection',
    Display: false,
  },
  { row: 8, Event: 'geoTypeChanged', PanelName: 'geoSearch', Display: false },
  {
    row: 9,
    Event: 'geoTypeChanged',
    PanelName: 'dataVariableSelection',
    Display: false,
  },
  { row: 11, Event: 'geoTypeChanged', PanelName: 'dashboard', Display: true },
  { row: 12, Event: 'geoTypeChanged', PanelName: 'legend', Display: true },
  {
    row: 13,
    Event: 'geographySelected',
    PanelName: 'industrySelection',
    Display: false,
  },
  {
    row: 14,
    Event: 'geographySelected',
    PanelName: 'geoSearch',
    Display: false,
  },
  {
    row: 15,
    Event: 'geographySelected',
    PanelName: 'dataVariableSelection',
    Display: false,
  },
  {
    row: 17,
    Event: 'geographySelected',
    PanelName: 'dashboard',
    Display: true,
  },
  { row: 18, Event: 'geographySelected', PanelName: 'legend', Display: true },
  {
    row: 19,
    Event: 'dataVariableChanged',
    PanelName: 'industrySelection',
    Display: false,
  },
  {
    row: 20,
    Event: 'dataVariableChanged',
    PanelName: 'geoSearch',
    Display: false,
  },
  {
    row: 21,
    Event: 'dataVariableChanged',
    PanelName: 'dataVariableSelection',
    Display: false,
  },
  {
    row: 23,
    Event: 'dataVariableChanged',
    PanelName: 'dashboard',
    Display: true,
  },
  {
    row: 24,
    Event: 'dataVariableChanged',
    PanelName: 'legend',
    Display: true,
  },
  {
    row: 25,
    Event: 'splashPageOnOpen',
    PanelName: 'industrySelection',
    Display: false,
  },
  {
    row: 26,
    Event: 'splashPageOnOpen',
    PanelName: 'geograhySelection',
    Display: false,
  },
  {
    row: 27,
    Event: 'splashPageOnOpen',
    PanelName: 'dataVariableSelection',
    Display: false,
  },
  {
    row: 29,
    Event: 'splashPageOnOpen',
    PanelName: 'dashboard',
    Display: true,
  },
  { row: 30, Event: 'splashPageOnOpen', PanelName: 'legend', Display: true },
  {
    row: 31,
    Event: 'splashPageOnClose',
    PanelName: 'industrySelection',
    Display: false,
  },
  {
    row: 32,
    Event: 'splashPageOnClose',
    PanelName: 'geograhySelection',
    Display: false,
  },
  {
    row: 33,
    Event: 'splashPageOnClose',
    PanelName: 'dataVariableSelection',
    Display: true,
  },
  {
    row: 36,
    Event: 'splashPageOnClose',
    PanelName: 'dashboard',
    Display: true,
  },
  { row: 38, Event: 'splashPageOnClose', PanelName: 'legend', Display: true },
  {
    row: 52,
    Event: 'filterCriteriaChanged',
    PanelName: 'industrySelection',
    Display: false,
  },
  {
    row: 53,
    Event: 'filterCriteriaChanged',
    PanelName: 'geograhySelection',
    Display: false,
  },
  {
    row: 54,
    Event: 'filterCriteriaChanged',
    PanelName: 'dataVariableSelection',
    Display: false,
  },
  {
    row: 56,
    Event: 'filterCriteriaChanged',
    PanelName: 'dashboard',
    Display: true,
  },
  {
    row: 57,
    Event: 'filterCriteriaChanged',
    PanelName: 'legend',
    Display: true,
  },
];
