export default [
  {
    row: 1,
    ID: 'p1',
    Name: '2014 American Community Survey 5-year Summary File',
    Program: 'ACS',
    Year: '2010-2014',
    Dataset: 'Summary File',
    API_URL: 'https://api.census.gov/data/2014/acs/acs5?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 2,
    ID: 'p2',
    Name: '2013 County Business Patterns',
    Program: 'ECON',
    Year: '2013',
    Dataset: 'CBP',
    API_URL: 'https://api.census.gov/data/2013/cbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 3,
    ID: 'p3',
    Name: '2013 Nonemployer Statistics',
    Program: 'ECON',
    Year: '2013',
    Dataset: 'NES',
    API_URL: 'https://api.census.gov/data/2013/nonemp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 4,
    ID: 'p4',
    Name: '2012 Economic Census',
    Program: 'ECON',
    Year: '2012',
    Dataset: 'EWKS',
    API_URL: 'https://api.census.gov/data/2012/ewks?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 5,
    ID: 'p5',
    Name: '2019 Esri Consumer Spending data',
    Program: 'ESRI',
    Year: '2019',
    Dataset: 'CS',
    API_URL: '${consumerDataAPIUrl}',
    MapTigerId: false,
    MapStateId: false,
    Source: 'ESRI_CONSUMER_DATA',
  },
  {
    row: 6,
    ID: 'p6',
    Name: '2012 Survey of Business Owners',
    Program: 'ECON',
    Year: '2012',
    Dataset: 'SBO',
    API_URL: 'https://api.census.gov/data/2012/sbo?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 7,
    ID: 'p7',
    Name: '2014 American Community Survey 5-year Data Profile',
    Program: 'ACS',
    Year: '2010-2014',
    Dataset: 'Data Profile',
    API_URL: 'https://api.census.gov/data/2014/acs/acs5/profile?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 9,
    ID: 'p9',
    Name: '2012 Nonemployer Statistics',
    Program: 'ECON',
    Year: '2012',
    Dataset: 'NES',
    API_URL: 'https://api.census.gov/data/2012/nonemp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 10,
    ID: 'p10',
    Name: '2012 American Community Survey 5-year Summary File',
    Program: 'ACS',
    Year: '2008-2012',
    Dataset: 'Summary File',
    API_URL: 'https://api.census.gov/data/2012/acs/acs5?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 11,
    ID: 'p11',
    Name: '2013 American Community Survey 5-year Summary File',
    Program: 'ACS',
    Year: '2009-2013',
    Dataset: 'Summary File',
    API_URL: 'https://api.census.gov/data/2013/acs/acs5?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 12,
    ID: 'p12',
    Name: '2013 American Community Survey 5-year Data Profile',
    Program: 'ACS',
    Year: '2009-2013',
    Dataset: 'Data Profile',
    API_URL: 'https://api.census.gov/data/2013/acs/acs5/profile?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 13,
    ID: 'p13',
    Name: '2007 Economic Census',
    Program: 'ECON',
    Year: '2007',
    Dataset: 'EWKS',
    API_URL: 'https://api.census.gov/data/2007/ewks?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 14,
    ID: 'p14',
    Name: '2011 County Business Patterns',
    Program: 'ECON',
    Year: '2011',
    Dataset: 'CBP',
    API_URL: 'https://api.census.gov/data/2011/cbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 15,
    ID: 'p15',
    Name: '2010 County Business Patterns',
    Program: 'ECON',
    Year: '2010',
    Dataset: 'CBP',
    API_URL: 'https://api.census.gov/data/2010/cbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 16,
    ID: 'p16',
    Name: '2009 County Business Patterns',
    Program: 'ECON',
    Year: '2009',
    Dataset: 'CBP',
    API_URL: 'https://api.census.gov/data/2009/cbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 17,
    ID: 'p17',
    Name: '2011 Nonemployer Statistics',
    Program: 'ECON',
    Year: '2011',
    Dataset: 'NES',
    API_URL: 'https://api.census.gov/data/2011/nonemp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 18,
    ID: 'p18',
    Name: '2010 Nonemployer Statistics',
    Program: 'ECON',
    Year: '2010',
    Dataset: 'NES',
    API_URL: 'https://api.census.gov/data/2010/nonemp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 19,
    ID: 'p19',
    Name: '2009 Nonemployer Statistics',
    Program: 'ECON',
    Year: '2009',
    Dataset: 'NES',
    API_URL: 'https://api.census.gov/data/2009/nonemp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 20,
    ID: 'p20',
    Name: '2009 American Community Survey 5-year Summary File',
    Program: 'ACS',
    Year: '2005-2009',
    Dataset: 'Summary File',
    API_URL: 'https://api.census.gov/data/2009/acs/acs5?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 21,
    ID: 'p21',
    Name: '2014 County Business Patterns',
    Program: 'ECON',
    Year: '2014',
    Dataset: 'CBP',
    API_URL: 'https://api.census.gov/data/2014/cbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 22,
    ID: 'p22',
    Name: '2014 Nonemployer Statistics',
    Program: 'ECON',
    Year: '2014',
    Dataset: 'NES',
    API_URL: 'https://api.census.gov/data/2014/nonemp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 23,
    ID: 'p23',
    Name: '2014 ZIP Code Business Patterns',
    Program: 'ECON',
    Year: '2014',
    Dataset: 'ZBP',
    API_URL: 'https://api.census.gov/data/2014/zbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 24,
    ID: 'p24',
    Name: '2015 American Community Survey 5-year Summary File',
    Program: 'ACS',
    Year: '2011-2015',
    Dataset: 'Summary File',
    API_URL: 'https://api.census.gov/data/2015/acs/acs5?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 25,
    ID: 'p25',
    Name: '2015 American Community Survey 5-year Data Profile',
    Program: 'ACS',
    Year: '2011-2015',
    Dataset: 'Data Profile',
    API_URL: 'https://api.census.gov/data/2015/acs/acs5/profile?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 26,
    ID: 'p26',
    Name: '2010 American Community Survey 5-year Summary File',
    Program: 'ACS',
    Year: '2006-2010',
    Dataset: 'Summary File',
    API_URL: 'https://api.census.gov/data/2010/acs/acs5?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 27,
    ID: 'p27',
    Name: '2010 American Community Survey 5-year Data Profile',
    Program: 'ACS',
    Year: '2006-2010',
    Dataset: 'Data Profile',
    API_URL: 'https://api.census.gov/data/2010/acs/acs5/profile?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 28,
    ID: 'p28',
    Name: '2015 County Business Patterns',
    Program: 'ECON',
    Year: '2015',
    Dataset: 'CBP',
    API_URL: 'https://api.census.gov/data/2015/cbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 29,
    ID: 'p29',
    Name: '2015 Nonemployer Statistics',
    Program: 'ECON',
    Year: '2015',
    Dataset: 'NES',
    API_URL: 'https://api.census.gov/data/2015/nonemp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 30,
    ID: 'p30',
    Name: '2016 International Trade: Imports',
    Program: 'ECON',
    Year: '2016',
    Dataset: 'TRADE',
    API_URL:
      'https://api.census.gov/data/timeseries/intltrade/imports/statenaics?',
    MapTigerId: false,
    MapStateId: true,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&${GEOTYPEID}=${geoIds}',
  },
  {
    row: 31,
    ID: 'p31',
    Name: '2016 International Trade: Exports',
    Program: 'ECON',
    Year: '2016',
    Dataset: 'TRADE',
    API_URL:
      'https://api.census.gov/data/timeseries/intltrade/exports/statenaics?',
    MapTigerId: false,
    MapStateId: true,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&${GEOTYPEID}=${geoIds}',
  },
  {
    row: 32,
    ID: 'p32',
    Name: '2012 Census of Agriculture',
    Program: 'ECON',
    Year: '2012',
    Dataset: 'AG',
    API_URL: '${consumerDataAPIUrl}',
    MapTigerId: false,
    MapStateId: false,
    Source: 'ESRI_CONSUMER_DATA',
  },
  {
    row: 33,
    ID: 'p33',
    Name: '2015 ZIP Code Business Patterns',
    Program: 'ECON',
    Year: '2015',
    Dataset: 'ZBP',
    API_URL: 'https://api.census.gov/data/2015/zbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 34,
    ID: 'p34',
    Name: '2013 ZIP Code Business Patterns',
    Program: 'ECON',
    Year: '2013',
    Dataset: 'ZBP',
    API_URL: 'https://api.census.gov/data/2013/zbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 35,
    ID: 'p35',
    Name: '2012 ZIP Code Business Patterns',
    Program: 'ECON',
    Year: '2012',
    Dataset: 'ZBP',
    API_URL: 'https://api.census.gov/data/2012/zbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 36,
    ID: 'p36',
    Name: '2011 ZIP Code Business Patterns',
    Program: 'ECON',
    Year: '2011',
    Dataset: 'ZBP',
    API_URL: 'https://api.census.gov/data/2011/zbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 37,
    ID: 'p37',
    Name: 'Quarterly Workforce Indicators',
    Program: 'ECON',
    Year: '2020Q4',
    Dataset: 'QWI',
    API_URL: 'https://api.census.gov/data/timeseries/qwi/sa?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'PREFIX_S',
  },
  {
    row: 38,
    ID: 'p38',
    Name: 'Quarterly Workforce Indicators',
    Program: 'ECON',
    Year: '2020Q3',
    Dataset: 'QWI',
    API_URL: 'https://api.census.gov/data/timeseries/qwi/sa?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'PREFIX_S',
  },
  {
    row: 39,
    ID: 'p39',
    Name: 'Quarterly Workforce Indicators',
    Program: 'ECON',
    Year: '2020Q2',
    Dataset: 'QWI',
    API_URL: 'https://api.census.gov/data/timeseries/qwi/sa?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'PREFIX_S',
  },
  {
    row: 40,
    ID: 'p40',
    Name: 'Quarterly Workforce Indicators',
    Program: 'ECON',
    Year: '2020Q1',
    Dataset: 'QWI',
    API_URL: 'https://api.census.gov/data/timeseries/qwi/sa?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'PREFIX_S',
  },
  {
    row: 41,
    ID: 'p41',
    Name: '2016 American Community Survey 5-year Summary File',
    Program: 'ACS',
    Year: '2012-2016',
    Dataset: 'Summary File',
    API_URL: 'https://api.census.gov/data/2016/acs/acs5?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 42,
    ID: 'p42',
    Name: '2016 American Community Survey 5-year Data Profile',
    Program: 'ACS',
    Year: '2012-2016',
    Dataset: 'Data Profile',
    API_URL: 'https://api.census.gov/data/2016/acs/acs5/profile?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 43,
    ID: 'p43',
    Name: '2011 American Community Survey 5-year Summary File',
    Program: 'ACS',
    Year: '2007-2011',
    Dataset: 'Summary File',
    API_URL: 'https://api.census.gov/data/2011/acs/acs5?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 44,
    ID: 'p44',
    Name: '2011 American Community Survey 5-year Data Profile',
    Program: 'ACS',
    Year: '2007-2011',
    Dataset: 'Data Profile',
    API_URL: 'https://api.census.gov/data/2011/acs/acs5/profile?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 45,
    ID: 'p45',
    Name: '2015 International Trade: Imports',
    Program: 'ECON',
    Year: '2015',
    Dataset: 'TRADE',
    API_URL:
      'https://api.census.gov/data/timeseries/intltrade/imports/statenaics?',
    MapTigerId: false,
    MapStateId: true,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&${GEOTYPEID}=${geoIds}',
  },
  {
    row: 46,
    ID: 'p46',
    Name: '2014 International Trade: Imports',
    Program: 'ECON',
    Year: '2014',
    Dataset: 'TRADE',
    API_URL:
      'https://api.census.gov/data/timeseries/intltrade/imports/statenaics?',
    MapTigerId: false,
    MapStateId: true,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&${GEOTYPEID}=${geoIds}',
  },
  {
    row: 47,
    ID: 'p47',
    Name: '2013 International Trade: Imports',
    Program: 'ECON',
    Year: '2013',
    Dataset: 'TRADE',
    API_URL:
      'https://api.census.gov/data/timeseries/intltrade/imports/statenaics?',
    MapTigerId: false,
    MapStateId: true,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&${GEOTYPEID}=${geoIds}',
  },
  {
    row: 48,
    ID: 'p48',
    Name: '2015 International Trade: Exports',
    Program: 'ECON',
    Year: '2015',
    Dataset: 'TRADE',
    API_URL:
      'https://api.census.gov/data/timeseries/intltrade/exports/statenaics?',
    MapTigerId: false,
    MapStateId: true,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&${GEOTYPEID}=${geoIds}',
  },
  {
    row: 49,
    ID: 'p49',
    Name: '2014 International Trade: Exports',
    Program: 'ECON',
    Year: '2014',
    Dataset: 'TRADE',
    API_URL:
      'https://api.census.gov/data/timeseries/intltrade/exports/statenaics?',
    MapTigerId: false,
    MapStateId: true,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&${GEOTYPEID}=${geoIds}',
  },
  {
    row: 50,
    ID: 'p50',
    Name: '2013 International Trade: Exports',
    Program: 'ECON',
    Year: '2013',
    Dataset: 'TRADE',
    API_URL:
      'https://api.census.gov/data/timeseries/intltrade/exports/statenaics?',
    MapTigerId: false,
    MapStateId: true,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&${GEOTYPEID}=${geoIds}',
  },
  {
    row: 51,
    ID: 'p51',
    Name: '2016 County Business Patterns',
    Program: 'ECON',
    Year: '2016',
    Dataset: 'CBP',
    API_URL: 'https://api.census.gov/data/2016/cbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 52,
    ID: 'p52',
    Name: '2016 ZIP Code Business Patterns',
    Program: 'ECON',
    Year: '2016',
    Dataset: 'ZBP',
    API_URL: 'https://api.census.gov/data/2016/zbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 53,
    ID: 'p53',
    Name: '2016 Nonemployer Statistics',
    Program: 'ECON',
    Year: '2016',
    Dataset: 'NES',
    API_URL: 'https://api.census.gov/data/2016/nonemp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 54,
    ID: 'p54',
    Name: '2017 International Trade: Imports',
    Program: 'ECON',
    Year: '2017',
    Dataset: 'TRADE',
    API_URL:
      'https://api.census.gov/data/timeseries/intltrade/imports/statenaics?',
    MapTigerId: false,
    MapStateId: true,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&${GEOTYPEID}=${geoIds}',
  },
  {
    row: 55,
    ID: 'p55',
    Name: '2017 International Trade: Exports',
    Program: 'ECON',
    Year: '2017',
    Dataset: 'TRADE',
    API_URL:
      'https://api.census.gov/data/timeseries/intltrade/exports/statenaics?',
    MapTigerId: false,
    MapStateId: true,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&${GEOTYPEID}=${geoIds}',
  },
  {
    row: 56,
    ID: 'p56',
    Name: '2018 Building Permits Survey',
    Program: 'ECON',
    Year: '2018',
    Dataset: 'BP',
    API_URL: '${consumerDataAPIUrl}',
    MapTigerId: false,
    MapStateId: false,
    Source: 'ESRI_CONSUMER_DATA',
  },
  {
    row: 57,
    ID: 'p57',
    Name: '2017 American Community Survey 5-year Summary File',
    Program: 'ACS',
    Year: '2013-2017',
    Dataset: 'Summary File',
    API_URL: 'https://api.census.gov/data/2017/acs/acs5?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 58,
    ID: 'p58',
    Name: '2017 American Community Survey 5-year Data Profile',
    Program: 'ACS',
    Year: '2013-2017',
    Dataset: 'Data Profile',
    API_URL: 'https://api.census.gov/data/2017/acs/acs5/profile?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 59,
    ID: 'p59',
    Name: 'Quarterly Census of Employment and Wages',
    Program: 'BLS',
    Year: '2021Q2',
    Dataset: 'BLS',
    API_URL: '${consumerDataAPIUrl}',
    MapTigerId: false,
    MapStateId: false,
    Source: 'ESRI_CONSUMER_DATA',
  },
  {
    row: 60,
    ID: 'p60',
    Name: 'Quarterly Census of Employment and Wages',
    Program: 'BLS',
    Year: '2021Q1',
    Dataset: 'BLS',
    API_URL: '${consumerDataAPIUrl}',
    MapTigerId: false,
    MapStateId: false,
    Source: 'ESRI_CONSUMER_DATA',
  },
  {
    row: 61,
    ID: 'p61',
    Name: 'Quarterly Census of Employment and Wages',
    Program: 'BLS',
    Year: '2020Q4',
    Dataset: 'BLS',
    API_URL: '${consumerDataAPIUrl}',
    MapTigerId: false,
    MapStateId: false,
    Source: 'ESRI_CONSUMER_DATA',
  },
  {
    row: 62,
    ID: 'p62',
    Name: 'Quarterly Census of Employment and Wages',
    Program: 'BLS',
    Year: '2020Q3',
    Dataset: 'BLS',
    API_URL: '${consumerDataAPIUrl}',
    MapTigerId: false,
    MapStateId: false,
    Source: 'ESRI_CONSUMER_DATA',
  },
  {
    row: 63,
    ID: 'p63',
    Name: 'Quarterly Census of Employment and Wages',
    Program: 'BLS',
    Year: '2020Q2',
    Dataset: 'BLS',
    API_URL: '${consumerDataAPIUrl}',
    MapTigerId: false,
    MapStateId: false,
    Source: 'ESRI_CONSUMER_DATA',
  },
  {
    row: 64,
    ID: 'p64',
    Name: 'Quarterly Census of Employment and Wages',
    Program: 'BLS',
    Year: '2021Q2',
    Dataset: 'BLS',
    API_URL: '${consumerDataAPIUrl}',
    MapTigerId: false,
    MapStateId: false,
    Source: 'ESRI_CONSUMER_DATA',
  },
  {
    row: 65,
    ID: 'p65',
    Name: 'Quarterly Census of Employment and Wages',
    Program: 'BLS',
    Year: '2020Q2',
    Dataset: 'BLS',
    API_URL: '${consumerDataAPIUrl}',
    MapTigerId: false,
    MapStateId: false,
    Source: 'ESRI_CONSUMER_DATA',
  },
  {
    row: 66,
    ID: 'p66',
    Name: 'Quarterly Census of Employment and Wages',
    Program: 'BLS',
    Year: '2019Q2',
    Dataset: 'BLS',
    API_URL: '${consumerDataAPIUrl}',
    MapTigerId: false,
    MapStateId: false,
    Source: 'ESRI_CONSUMER_DATA',
  },
  {
    row: 67,
    ID: 'p67',
    Name: 'Quarterly Census of Employment and Wages',
    Program: 'BLS',
    Year: '2018Q2',
    Dataset: 'BLS',
    API_URL: '${consumerDataAPIUrl}',
    MapTigerId: false,
    MapStateId: false,
    Source: 'ESRI_CONSUMER_DATA',
  },
  {
    row: 68,
    ID: 'p68',
    Name: 'Quarterly Census of Employment and Wages',
    Program: 'BLS',
    Year: '2017Q2',
    Dataset: 'BLS',
    API_URL: '${consumerDataAPIUrl}',
    MapTigerId: false,
    MapStateId: false,
    Source: 'ESRI_CONSUMER_DATA',
  },
  {
    row: 69,
    ID: 'p69',
    Name: '2018 International Trade: Imports',
    Program: 'ECON',
    Year: '2018',
    Dataset: 'TRADE',
    API_URL:
      'https://api.census.gov/data/timeseries/intltrade/imports/statenaics?',
    MapTigerId: false,
    MapStateId: true,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&${GEOTYPEID}=${geoIds}',
  },
  {
    row: 70,
    ID: 'p70',
    Name: '2018 International Trade: Exports',
    Program: 'ECON',
    Year: '2018',
    Dataset: 'TRADE',
    API_URL:
      'https://api.census.gov/data/timeseries/intltrade/exports/statenaics?',
    MapTigerId: false,
    MapStateId: true,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&${GEOTYPEID}=${geoIds}',
  },
  {
    row: 71,
    ID: 'p71',
    Name: '2017 Nonemployer Statistics',
    Program: 'ECON',
    Year: '2017',
    Dataset: 'NES',
    API_URL: 'https://api.census.gov/data/2017/nonemp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 72,
    ID: 'p72',
    Name: '2017 County Business Patterns',
    Program: 'ECON',
    Year: '2017',
    Dataset: 'CBP',
    API_URL: 'https://api.census.gov/data/2017/cbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 73,
    ID: 'p73',
    Name: '2017 ZIP Code Business Patterns',
    Program: 'ECON',
    Year: '2017',
    Dataset: 'ZBP',
    API_URL: 'https://api.census.gov/data/2017/zbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 74,
    ID: 'p74',
    Name: '2018 American Community Survey 5-year Summary File',
    Program: 'ACS',
    Year: '2014-2018',
    Dataset: 'Summary File',
    API_URL: 'https://api.census.gov/data/2018/acs/acs5?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 75,
    ID: 'p75',
    Name: '2018 American Community Survey 5-year Data Profile',
    Program: 'ACS',
    Year: '2014-2018',
    Dataset: 'Data Profile',
    API_URL: 'https://api.census.gov/data/2018/acs/acs5/profile?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 76,
    ID: 'p76',
    Name: '2019 Building Permits Survey',
    Program: 'ECON',
    Year: '2019',
    Dataset: 'BP',
    API_URL: '${consumerDataAPIUrl}',
    MapTigerId: false,
    MapStateId: false,
    Source: 'ESRI_CONSUMER_DATA',
  },
  {
    row: 77,
    ID: 'p77',
    Name: '2017 Economic Census',
    Program: 'ECON',
    Year: '2017',
    Dataset: 'EWKS',
    API_URL: 'https://api.census.gov/data/2017/ecnbasic?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 79,
    ID: 'p79',
    Name: '2018 Nonemployer Statistics',
    Program: 'ECON',
    Year: '2018',
    Dataset: 'NES',
    API_URL: 'https://api.census.gov/data/2018/nonemp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 80,
    ID: 'p80',
    Name: 'Quarterly Workforce Indicators',
    Program: 'ECON',
    Year: '2020Q4',
    Dataset: 'QWI',
    API_URL: 'https://api.census.gov/data/timeseries/qwi/se?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'PREFIX_S',
  },
  {
    row: 81,
    ID: 'p81',
    Name: 'Quarterly Workforce Indicators',
    Program: 'ECON',
    Year: '2020Q3',
    Dataset: 'QWI',
    API_URL: 'https://api.census.gov/data/timeseries/qwi/se?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'PREFIX_S',
  },
  {
    row: 82,
    ID: 'p82',
    Name: 'Quarterly Workforce Indicators',
    Program: 'ECON',
    Year: '2020Q2',
    Dataset: 'QWI',
    API_URL: 'https://api.census.gov/data/timeseries/qwi/se?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'PREFIX_S',
  },
  {
    row: 83,
    ID: 'p83',
    Name: 'Quarterly Workforce Indicators',
    Program: 'ECON',
    Year: '2020Q1',
    Dataset: 'QWI',
    API_URL: 'https://api.census.gov/data/timeseries/qwi/se?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'PREFIX_S',
  },
  {
    row: 84,
    ID: 'p84',
    Name: '2019 International Trade: Imports',
    Program: 'ECON',
    Year: '2019',
    Dataset: 'TRADE',
    API_URL:
      'https://api.census.gov/data/timeseries/intltrade/imports/statenaics?',
    MapTigerId: false,
    MapStateId: true,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&${GEOTYPEID}=${geoIds}',
  },
  {
    row: 85,
    ID: 'p85',
    Name: '2019 International Trade: Exports',
    Program: 'ECON',
    Year: '2019',
    Dataset: 'TRADE',
    API_URL:
      'https://api.census.gov/data/timeseries/intltrade/exports/statenaics?',
    MapTigerId: false,
    MapStateId: true,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&${GEOTYPEID}=${geoIds}',
  },
  {
    row: 86,
    ID: 'p86',
    Name: '2018 County Business Patterns',
    Program: 'ECON',
    Year: '2018',
    Dataset: 'CBP',
    API_URL: 'https://api.census.gov/data/2018/cbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 87,
    ID: 'p87',
    Name: '2019 American Community Survey 5-year Summary File',
    Program: 'ACS',
    Year: '2015-2019',
    Dataset: 'Summary File',
    API_URL: 'https://api.census.gov/data/2019/acs/acs5?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 88,
    ID: 'p88',
    Name: '2019 American Community Survey 5-year Data Profile',
    Program: 'ACS',
    Year: '2015-2019',
    Dataset: 'Data Profile',
    API_URL: 'https://api.census.gov/data/2019/acs/acs5/profile?',
    MapTigerId: true,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    ReliabilityStrategy: 'ACS_MOE',
  },
  {
    row: 89,
    ID: 'p89',
    Name: '2018 ZIP Code Business Patterns',
    Program: 'ECON',
    Year: '2018',
    Dataset: 'ZBP',
    API_URL: 'https://api.census.gov/data/2018/zbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 90,
    ID: 'p90',
    Name: '2019 County Business Patterns',
    Program: 'ECON',
    Year: '2019',
    Dataset: 'CBP',
    API_URL: 'https://api.census.gov/data/2019/cbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 91,
    ID: 'p91',
    Name: '2019 ZIP Code Business Patterns',
    Program: 'ECON',
    Year: '2019',
    Dataset: 'ZBP',
    API_URL: 'https://api.census.gov/data/2019/zbp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
  {
    row: 92,
    ID: 'p92',
    Name: '2020 Building Permits Survey',
    Program: 'ECON',
    Year: '2020',
    Dataset: 'BP',
    API_URL: '${consumerDataAPIUrl}',
    MapTigerId: false,
    MapStateId: false,
    Source: 'ESRI_CONSUMER_DATA',
  },
  {
    row: 93,
    ID: 'p93',
    Name: '2020 International Trade: Imports',
    Program: 'ECON',
    Year: '2020',
    Dataset: 'TRADE',
    API_URL:
      'https://api.census.gov/data/timeseries/intltrade/imports/statenaics?',
    MapTigerId: false,
    MapStateId: true,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&${GEOTYPEID}=${geoIds}',
  },
  {
    row: 94,
    ID: 'p94',
    Name: '2020 International Trade: Exports',
    Program: 'ECON',
    Year: '2020',
    Dataset: 'TRADE',
    API_URL:
      'https://api.census.gov/data/timeseries/intltrade/exports/statenaics?',
    MapTigerId: false,
    MapStateId: true,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&${GEOTYPEID}=${geoIds}',
  },
  {
    row: 95,
    ID: 'p95',
    Name: '2021 Esri Consumer Spending data',
    Program: 'ESRI',
    Year: '2021',
    Dataset: 'CS',
    API_URL: '${consumerDataAPIUrl}',
    MapTigerId: false,
    MapStateId: false,
    Source: 'ESRI_CONSUMER_DATA',
  },
  {
    row: 96,
    ID: 'p96',
    Name: '2019 Nonemployer Statistics',
    Program: 'ECON',
    Year: '2019',
    Dataset: 'NES',
    API_URL: 'https://api.census.gov/data/2019/nonemp?',
    MapTigerId: false,
    MapStateId: false,
    Source: 'CENSUS_DATA_API',
    GeoFormat: '&for=${geotypeId}:${geoIds}?&in=${inClause}',
    FlagStrategy: 'UNDERSCORE_F',
  },
];
