export default [
  {
    row: 1,
    ID: 'Construction',
    Name: 'Construction',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'Construction.png',
    Image_Hover: 'con_on.png',
    PopUpTip:
      'Construction - Includes Drywall, Electrical, Flooring, Foundation, Home Construction, Nonresidental Construction, Painting and Wallpapering, Plumbing, and Tile Contractors',
  },
  {
    row: 2,
    ID: 'Food Services',
    Name: 'Food Services',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'food.png',
    Image_Hover: 'food_on.png',
    PopUpTip:
      'Food Services - Includes Bars, Buffets, Caterers, Full-Service and Fast Food Restaurants, Food Contractors, Food Trucks, and Snack Bars',
  },
  {
    row: 3,
    ID: 'Health Care',
    Name: 'Health Care',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'health.png',
    Image_Hover: 'health_on.png',
    PopUpTip:
      'Health Care - Includes Assisted Living Facilities; Offices of Chiropractors, Dentists, Doctors, Optometrists, and Therapists; Home Health Care; and Mental Health, and Outpatient Care Facilities',
  },
  {
    row: 4,
    ID: 'Personal Services',
    Name: 'Personal Services',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'pers.png',
    Image_Hover: 'pers_on.png',
    PopUpTip:
      'Personal Services - Includes Auto Repair and Barber Shops, Beauty Salons, Day Care, Landscaping Services, Nail Salons, Photographers, Taxi Services, and Travel Agencies',
  },
  {
    row: 5,
    ID: 'Professional Services',
    Name: 'Prof & Biz Services',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'professionalservices.png',
    Image_Hover: 'professionalservices_on.png',
    PopUpTip:
      'Prof & Biz Services - Includes Offices of Accountants and Architects, Consulting Firms, Insurance Agencies, Janitorial Services, Lawyers and Real Estate Offices, Systems Design, and Trucking',
  },
  {
    row: 6,
    ID: 'Retail',
    Name: 'Retail',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'retail.png',
    Image_Hover: 'retail_on.png',
    PopUpTip:
      'Retail - Includes Clothing and Convenience Stores, Direct Sales, Florists, Gas Stations, Liquor Stores, Online/Mail Order, Pharmacies, and Used Car Dealers',
  },
  {
    row: 7,
    ID: '23831',
    Name: 'Drywall',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'drywall.png',
    Image_Hover: 'drywall_on.png',
    PopUpTip:
      'Drywall - Includes businesses that primarily perform drywall, plaster work, and building insulation work (NAICS 23831)',
    ParentID: 'Construction',
  },
  {
    row: 8,
    ID: '23821',
    Name: 'Electrical',
    isNaicsIndustry: 'UNKNOWN',
    Image: '23821.png',
    Image_Hover: '23821_on.png',
    PopUpTip:
      'Electrical - Includes businesses that primarily install and service electrical wiring and equipment (NAICS 23821)',
    ParentID: 'Construction',
  },
  {
    row: 9,
    ID: '23833',
    Name: 'Flooring',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'Flooring.png',
    Image_Hover: 'Flooring_on.png',
    PopUpTip:
      'Flooring - Includes businesses that primarily install resilient floor tile, carpeting, and hardwood flooring (NAICS 23833)',
    ParentID: 'Construction',
  },
  {
    row: 10,
    ID: '2381',
    Name: 'Foundations',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'foundations.png',
    Image_Hover: 'foundations_on.png',
    PopUpTip:
      'Foundations - Includes businesses that primarily complete the basic structure (i.e., foundation, frame, and shell) of buildings (NAICS 2381)',
    ParentID: 'Construction',
  },
  {
    row: 11,
    ID: '2361',
    Name: 'Home Construction',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'homeconst.png',
    Image_Hover: 'homeconst_on.png',
    PopUpTip:
      'Home Construction - Includes businesses that primarily are responsible for the construction or remodeling and renovation of single-family and multifamily residential buildings (NAICS 2361)',
    ParentID: 'Construction',
  },
  {
    row: 12,
    ID: '2362',
    Name: 'Nonresidential',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'nonresidential.png',
    Image_Hover: 'nonresidential_on.png',
    PopUpTip:
      'Nonresidential - Includes businesses that primarily perform construction (including new work, additions, alterations, maintenance, and repairs) of nonresidential (industrial, commercial, and institutional) buildings (NAICS 2362)',
    ParentID: 'Construction',
  },
  {
    row: 13,
    ID: '23832',
    Name: 'Painting and Wall Paper',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'Painting.png',
    Image_Hover: 'Painting_on.png',
    PopUpTip:
      'Painting and wall paper - Includes businesses primarily engaged in interior or exterior painting or interior wall covering (NAICS 23832)',
    ParentID: 'Construction',
  },
  {
    row: 14,
    ID: '23822',
    Name: 'Plumbing',
    isNaicsIndustry: 'UNKNOWN',
    Image: '23822.png',
    Image_Hover: '23822_on.png',
    PopUpTip:
      'Plumbing - Includes businesses that primarily install and service plumbing, heating, and air-conditioning equipment (NAICS 23822)',
    ParentID: 'Construction',
  },
  {
    row: 15,
    ID: '23834',
    Name: 'Tile',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'tile.png',
    Image_Hover: 'tile_on.png',
    PopUpTip:
      'Tile - Includes businesses that primarily set and install ceramic tile, stone (interior only), and mosaic and/or mixing marble particles and cement to make terrazzo at the job site (NAICS 23834)',
    ParentID: 'Construction',
  },
  {
    row: 16,
    ID: '311811',
    Name: 'Bakeries',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'Bakeries.png',
    Image_Hover: 'Bakeries_on.png',
    PopUpTip:
      'Retail Bakeries - Includes businesses that primarily retail bread and other bakery products made on the premises from flour (and not prepared dough) and not for immediate consumption (NAICS 311811)',
    ParentID: 'Food Services',
  },
  {
    row: 17,
    ID: '7224',
    Name: 'Bars',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'Bars.png',
    Image_Hover: 'Bars_on.png',
    PopUpTip:
      'Bars - Includes businesses known as bars, taverns, or night clubs that serve alcoholic beverages for immediate consumption and may also provide limited food services (NAICS 7224)',
    ParentID: 'Food Services',
  },
  {
    row: 18,
    ID: '722514',
    Name: 'Buffets',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'buffets.png',
    Image_Hover: 'buffets_on.png',
    PopUpTip:
      'Buffets - Includes businesses, known as cafeterias, grill buffets, or buffets, that primarily prepare and serve meals for immediate consumption using cafeteria-style or buffet serving equipment (NAICS 722514)',
    ParentID: 'Food Services',
  },
  {
    row: 19,
    ID: '72232',
    Name: 'Caterers',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'Caterers.png',
    Image_Hover: 'Caterers_on.png',
    PopUpTip:
      'Caterers - Includes businesses that primarily provide single-event food services, with food prepared off-site and transported to the event site. Also includes banquet halls with catering staff (NAICS 72232)',
    ParentID: 'Food Services',
  },
  {
    row: 20,
    ID: '722511',
    Name: 'Restaurants',
    isNaicsIndustry: 'UNKNOWN',
    Image: '7221.png',
    Image_Hover: '7221_on.png',
    PopUpTip:
      'Restaurants - Includes businesses that primarily provide food services to patrons who order and are served while seated and pay after eating (NAICS 722511)',
    ParentID: 'Food Services',
  },
  {
    row: 21,
    ID: '722513',
    Name: 'Fast Food',
    isNaicsIndustry: 'UNKNOWN',
    Image: '7222.png',
    Image_Hover: '7222_on.png',
    PopUpTip:
      'Fast Food - Includes businesses that primarily provide food services where patrons order and pay before eating, and where the food can be consumed on-site, carried out, or delivered (NAICS 722513)',
    ParentID: 'Food Services',
  },
  {
    row: 22,
    ID: '72231',
    Name: 'Food Contractors',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'foodcontractors.png',
    Image_Hover: 'foodcontractors_on.png',
    PopUpTip:
      'Food Contractors - Includes businesses that primarily provide food services at institutional, governmental, commercial, or industrial locations of others (NAICS 72231)',
    ParentID: 'Food Services',
  },
  {
    row: 23,
    ID: '72233',
    Name: 'Food Trucks',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'foodtrucks.png',
    Image_Hover: 'foodtrucks_on.png',
    PopUpTip:
      'Food trucks - Includes businesses that primarily prepare and serve meals and snacks for immediate consumption from motorized vehicles or nonmotorized carts (NAICS 72233)',
    ParentID: 'Food Services',
  },
  {
    row: 24,
    ID: '722515',
    Name: 'Snack Bars',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'snack.png',
    Image_Hover: 'snack_on.png',
    PopUpTip:
      'Snack bars - Includes businesses that primarily prepare and/or serve specialty snacks (such as ice cream, frozen yogurt, cookies, or popcorn) or serve nonalcoholic beverages (such as coffee, juices, or sodas) for consumption on or near the premises (NAICS 722515)',
    ParentID: 'Food Services',
  },
  {
    row: 25,
    ID: '623312',
    Name: 'Assisted Living',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'assisted.png',
    Image_Hover: 'assisted_on.png',
    PopUpTip:
      'Assisted living - Includes businesses that primarily provide residential and personal care services for the elderly or other persons who are unable to fully care for themselves and/or live independently (NAICS 623312)',
    ParentID: 'Health Care',
  },
  {
    row: 26,
    ID: '62131',
    Name: 'Chiropractors',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'Chiropractors.png',
    Image_Hover: 'Chiropractors_on.png',
    PopUpTip:
      'Chiropractors - Includes businesses that primarily provide independent chiropractic care in their own offices or in the offices of others (NAICS 62131)',
    ParentID: 'Health Care',
  },
  {
    row: 27,
    ID: '6212',
    Name: 'Dentists',
    isNaicsIndustry: 'UNKNOWN',
    Image: '62121.png',
    Image_Hover: '62121_on.png',
    PopUpTip:
      'Dentists - Includes businesses that primarily provide independent general dental care or dental surgery in their own offices or in the offices of others (NAICS 6212)',
    ParentID: 'Health Care',
  },
  {
    row: 28,
    ID: '6211',
    Name: 'Doctors',
    isNaicsIndustry: 'UNKNOWN',
    Image: '62111.png',
    Image_Hover: '62111_on.png',
    PopUpTip:
      'Doctors - Includes businesses that primarily provide independent general or specialized medical care (except psychiatry) in their own offices or in the offices of others (NAICS 6211)',
    ParentID: 'Health Care',
  },
  {
    row: 29,
    ID: '6216',
    Name: 'Home Health Care',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'homehealth.png',
    Image_Hover: 'homehealth_on.png',
    PopUpTip:
      'Home Health Care - Includes businesses that primarily provide skilled nursing services in the home, as well as personal care services, homemaker and companion services, physical therapy, etc. (NAICS 6216)',
    ParentID: 'Health Care',
  },
  {
    row: 30,
    ID: '62133',
    Name: 'Mental Health',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'mental.png',
    Image_Hover: 'mental_on.png',
    PopUpTip:
      'Mental Health - Includes businesses that primarily diagnose and treat mental, emotional, and behavioral disorders, or individual or group social dysfunction (NAICS 62133)',
    ParentID: 'Health Care',
  },
  {
    row: 31,
    ID: '62132',
    Name: 'Optometrists',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'Optometrists.png',
    Image_Hover: 'Optometrists_on.png',
    PopUpTip:
      'Optometrists - Includes businesses that primarily provide independent optometry care in their own offices or in the offices of others (NAICS 62132)',
    ParentID: 'Health Care',
  },
  {
    row: 32,
    ID: '6214',
    Name: 'Outpatient Care',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'outpatient.png',
    Image_Hover: 'outpatient_on.png',
    PopUpTip:
      'Outpatient care - Includes businesses that primarily provide a range of outpatient services such as family planning, diagnosis and treatment of mental health disorders, alcohol and other substance abuse, pain therapy, and sleep disorders (NAICS 6214)',
    ParentID: 'Health Care',
  },
  {
    row: 33,
    ID: '62134',
    Name: 'Therapists',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'Therapists.png',
    Image_Hover: 'Therapists_on.png',
    PopUpTip:
      'Therapists - Includes businesses that primarily provide independent physical, occupational, or speech therapy in their own offices or in the offices of others (NAICS 62134)',
    ParentID: 'Health Care',
  },
  {
    row: 34,
    ID: '8111',
    Name: 'Auto Repair',
    isNaicsIndustry: 'UNKNOWN',
    Image: '8111.png',
    Image_Hover: '8111_on.png',
    PopUpTip:
      'Auto repair - Includes businesses that primarily provide repair and maintenance services (including electrical and body) for cars, trucks, vans, and trailers (NAICS 8111)',
    ParentID: 'Personal Services',
  },
  {
    row: 35,
    ID: '812111',
    Name: 'Barber Shops',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'barber.png',
    Image_Hover: 'barber_on.png',
    PopUpTip:
      "Barber shops - Includes businesses that primarily cut, trim, and style men's and boys' hair, and/or shave and trim men's beards (NAICS 812111)",
    ParentID: 'Personal Services',
  },
  {
    row: 36,
    ID: '812112',
    Name: 'Beauty Salons',
    isNaicsIndustry: 'UNKNOWN',
    Image: '812112.png',
    Image_Hover: '812112_on.png',
    PopUpTip:
      "Beauty salons - Includes businesses that primarily provide hair cuts and styling, facials, and makeup services. Excludes barber shops and men's hair stylist shops (NAICS 812112)",
    ParentID: 'Personal Services',
  },
  {
    row: 37,
    ID: '6244',
    Name: 'Child Day Care',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'Daycare.png',
    Image_Hover: 'Daycare_on.png',
    PopUpTip:
      'Day Care - Includes businesses that primarily provide day care of infants or children and may also offer pre-K educational programs (NAICS 6244)',
    ParentID: 'Personal Services',
  },
  {
    row: 38,
    ID: '56173',
    Name: 'Landscaping',
    isNaicsIndustry: 'UNKNOWN',
    Image: '56173.png',
    Image_Hover: '56173_on.png',
    PopUpTip:
      'Landscaping - Includes businesses that primarily provide landscape care, maintenance, design, and installation services (NAICS 56173)',
    ParentID: 'Personal Services',
  },
  {
    row: 39,
    ID: '812113',
    Name: 'Nail Salons',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'nail.png',
    Image_Hover: 'nail_on.png',
    PopUpTip:
      'Nail salons - Includes businesses that primarily provide nail care services, such as manicures, pedicures, and nail extensions (NAICS 812113)',
    ParentID: 'Personal Services',
  },
  {
    row: 40,
    ID: '54192',
    Name: 'Photographers',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'photographers.png',
    Image_Hover: 'photographers_on.png',
    PopUpTip:
      'Photographers - Includes businesses that primarily provide still, video, or digital photography services (NAICS 54192)',
    ParentID: 'Personal Services',
  },
  {
    row: 41,
    ID: '48531',
    Name: 'Taxi Services',
    isNaicsIndustry: 'UNKNOWN',
    Image: '48531.png',
    Image_Hover: '48531_on.png',
    PopUpTip:
      'Taxi services - Includes businesses that primarily provide passenger transportation by car or van and not opperated on regular routes or schedules (NAICS 48531)',
    ParentID: 'Personal Services',
  },
  {
    row: 42,
    ID: '56151',
    Name: 'Travel Agencies',
    isNaicsIndustry: 'UNKNOWN',
    Image: '56151.png',
    Image_Hover: '56151_on.png',
    PopUpTip:
      'Travel agencies - Includes businesses that primarily sell travel, tour, and accommodations services to the general public and commercial clients (NAICS 56151)',
    ParentID: 'Personal Services',
  },
  {
    row: 43,
    ID: '5412',
    Name: 'Accounting ',
    isNaicsIndustry: 'UNKNOWN',
    Image: '54121.png',
    Image_Hover: '54121_on.png',
    PopUpTip:
      'Accounting  - Includes businesses that primarily provide accounting, tax preparation, bookkeeping, and payroll services (NAICS 5412)',
    ParentID: 'Professional Services',
  },
  {
    row: 44,
    ID: '54131',
    Name: 'Architects',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'architects.png',
    Image_Hover: 'architects_on.png',
    PopUpTip:
      'Architects - Includes businesses that primarily plan and design residential, institutional, leisure, commercial, and industrial buildings and structures (NAICS 54131)',
    ParentID: 'Professional Services',
  },
  {
    row: 45,
    ID: '54161',
    Name: 'Consulting',
    isNaicsIndustry: 'UNKNOWN',
    Image: '54161.png',
    Image_Hover: 'Consulting_on.png',
    PopUpTip:
      'Consulting - Includes businesses that primarily provide advice and assistance to businesses and other organizations on planning, marketing, and policy issues (NAICS 54161)',
    ParentID: 'Professional Services',
  },
  {
    row: 46,
    ID: '52421',
    Name: 'Insurance',
    isNaicsIndustry: 'UNKNOWN',
    Image: '52421.png',
    Image_Hover: '52421_on.png',
    PopUpTip:
      'Insurance - Includes businesses that primarily act as agents in selling annuities and insurance policies (NAICS 52421)',
    ParentID: 'Professional Services',
  },
  {
    row: 47,
    ID: '56172',
    Name: 'Janitorial Services',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'janitorial.png',
    Image_Hover: 'janitorial_on.png',
    PopUpTip:
      'Janitorial Services - Includes buisinesses that primarily clean building interiors, interiors of transportation equipment, and/or windows (NAICS 56172)',
    ParentID: 'Professional Services',
  },
  {
    row: 48,
    ID: '54111',
    Name: 'Lawyers',
    isNaicsIndustry: 'UNKNOWN',
    Image: '54111.png',
    Image_Hover: '54111_on.png',
    PopUpTip:
      'Lawyers - Includes businesses that primarily practice criminal, corporate, family and estate, real estate, and tax law (NAICS 54111)',
    ParentID: 'Professional Services',
  },
  {
    row: 49,
    ID: '5312',
    Name: 'Real Estate',
    isNaicsIndustry: 'UNKNOWN',
    Image: '53121.png',
    Image_Hover: '53121_on.png',
    PopUpTip:
      'Real Estate - Includes businesses that primarily act as agents in selling, buying, or renting real estate for others (NAICS 5312)',
    ParentID: 'Professional Services',
  },
  {
    row: 50,
    ID: '5415',
    Name: 'Systems Design',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'sysdesign.png',
    Image_Hover: 'sysdesign_on.png',
    PopUpTip:
      'Systems Design - Includes businesses that primarily provide IT expertise through software development, computer systems integration, on-site computer systems management, and other computer-related advice and services (NAICS 5415)',
    ParentID: 'Professional Services',
  },
  {
    row: 51,
    ID: '4841',
    Name: 'Trucking',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'trucking.png',
    Image_Hover: 'trucking_on.png',
    PopUpTip:
      'Trucking - Includes businesses that primarily provide general freight trucking, including both local and long-distance (NAICS 4841)',
    ParentID: 'Professional Services',
  },
  {
    row: 52,
    ID: '4481',
    Name: 'Clothing Stores',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'clothingstores.png',
    Image_Hover: 'clothingstores_on.png',
    PopUpTip:
      'Clothing Stores - Includes businesses that primarily retail new clothing (NAICS 4481)',
    ParentID: 'Retail',
  },
  {
    row: 53,
    ID: '44512',
    Name: 'Convenience Stores',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'ConvenienceStores.png',
    Image_Hover: 'ConvenienceStores_on.png',
    PopUpTip:
      'Convenience Stores - Includes businesses that primarily sell a limited line of goods. Excludes convenience stores with fuel pumps (NAICS 44512)',
    ParentID: 'Retail',
  },
  {
    row: 54,
    ID: '4543',
    Name: 'Direct Sales',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'direct.png',
    Image_Hover: 'direct_on.png',
    PopUpTip:
      "Direct Sales - Includes businesses that primarily go to the customers' location rather than the customer coming to them (e.g., door-to-door sales, home parties). This excludes on-line, mail order, and vending machines, but includes home delivery newspaper routes, home delivery of heating oil, liquefied petroleum (LP) gas, and other fuels; locker meat provisioners; frozen food and freezer plan providers; coffee-break services providers; and bottled water or water softener services (NAICS 4543)",
    ParentID: 'Retail',
  },
  {
    row: 55,
    ID: '4531',
    Name: 'Florists',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'Florists.png',
    Image_Hover: 'Florists_on.png',
    PopUpTip:
      'Florists - Includes businesses that primarily retail cut flowers, floral arrangements, and potted plants purchased from others (NAICS 4531)',
    ParentID: 'Retail',
  },
  {
    row: 56,
    ID: '4471',
    Name: 'Gas Stations',
    isNaicsIndustry: 'UNKNOWN',
    Image: '4471.png',
    Image_Hover: '4471_on.png',
    PopUpTip:
      'Gas Stations - Includes businesses that primarily retail automotive fuels in combination with (or without) a convenience store or repair facility (NAICS 4471)',
    ParentID: 'Retail',
  },
  {
    row: 57,
    ID: '4453',
    Name: 'Liquor Stores',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'LiquorStores.png',
    Image_Hover: 'LiquorStores_on.png',
    PopUpTip:
      'Liquor Stores - Includes businesses that primarily retail packaged ale, wine, beer, and liquor (NAICS 4453)',
    ParentID: 'Retail',
  },
  {
    row: 58,
    ID: '4541',
    Name: 'Online/Mail Order',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'online.png',
    Image_Hover: 'online_on.png',
    PopUpTip:
      'Online/Mail Order - Includes businesses that primarily retail all types of merchandise using non-store means, such as catalogs, toll free telephone numbers, electronic media, or mail-order houses (NAICS 4541)',
    ParentID: 'Retail',
  },
  {
    row: 59,
    ID: '44611',
    Name: 'Pharmacies',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'pharmacies.png',
    Image_Hover: 'pharmacies_on.png',
    PopUpTip:
      'Pharmacies - Includes businesses that retail prescription or nonprescription drugs and medicines (NAICS 44611)',
    ParentID: 'Retail',
  },
  {
    row: 60,
    ID: '44112',
    Name: 'Used Car Dealers',
    isNaicsIndustry: 'UNKNOWN',
    Image: 'UsedCarDealers.png',
    Image_Hover: 'UsedCarDealers_on.png',
    PopUpTip:
      'Used Car Dealers - Includes businesses that primarily retail used automobiles and light trucks (NAICS 44112)',
    ParentID: 'Retail',
  },
];
